# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "84d6cd3efe9abb7ff3935c93504c8c7c"
name = "extension-discount-free"
handle = "extension-discount-free"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "edindev-functions.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_cart_transforms,write_cart_transforms,write_products,read_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
